services:
  mcp-server:
    container_name: mcp-dent
    build:
      context: .
      dockerfile: docker/Dockerfile.mcp
    ports:
      - "8001:8001"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - general-network

  api:
    container_name: api-dent
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - general-network

  bot:
    container_name: bot-dent
    build:
      context: .
      dockerfile: docker/Dockerfile.bot
    env_file:
      - .env
    depends_on:
      - mcp-server
    restart: unless-stopped
    networks:
      - general-network

  dashboard:
    container_name: dashboard-dent
    build:
      context: .
      dockerfile: docker/Dockerfile.dashboard
    ports:
      - "8502:8502"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - general-network

networks:
  general-network:
    external: true

